// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ImageViewer: typeof import('./src/components/ImageViewer.vue')['default']
    ListPosts: typeof import('./src/components/ListPosts.vue')['default']
    Masonry: typeof import('./src/components/Masonry.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    Post: typeof import('./src/components/Post.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
